// servers/home/core/Constants.tsx
var STATES = {
  PREP: "prep",
  GROW: "grow",
  HACK: "hack"
};
var START_SCRIPT_TIME = 5e3;
var BASE_BACKGROUND_COLOR = "#000000";
var CONTENT_BACKGROUND_COLOR = "#1A1C24";
var TRINARY_BACKGROUND_COLOR = "#25293b";
export {
  BASE_BACKGROUND_COLOR,
  CONTENT_BACKGROUND_COLOR,
  START_SCRIPT_TIME,
  STATES,
  TRINARY_BACKGROUND_COLOR
};
